// Site-wide configuration — edit these values to customize
export const CONFIG = {
  brand: {
    name: 'OUR CREATIVE WORKS',
    shortName: 'OCW',
    tagline: 'FILMMAKERS • CREATORS • EDITORS • VISUAL STORYTELLERS',
    founder: 'SAIKUMAR',
    role: 'Founder & Creative Director',
    email: 'saikumar89515@gmail.com',
    phone: '+91 9014002314',
    location: 'NELLORE',
    instagram: 'https://www.instagram.com/our_creative_works/',
    youtube: 'https://youtube.com/',
  },
  stats: [
    { value: '25+', label: 'Creative Services', suffix: '' },
    { value: '100+', label: 'Projects Delivered', suffix: '' },
    { value: '5+', label: 'Years of Experience', suffix: '' },
    { value: '∞', label: 'Ideas', suffix: '' },
  ],
  services: [
    {
      id: 'reel-shoots-iphones',
      number: '01',
      title: 'REEL SHOOTS (IPHONE)',
      description: 'Fast delivery & best quality Reel shoots captured on iPhones for maximum social media engagement.',
      image: '/iphone_gimbal.jpg',
      features: [
        'Fast Delivery',
        'Best Quality on iPhone',
        'Trending Transitions & Edits',
        'Custom Color Grading',
        'Optimized for Reels & Shorts'
      ]
    },
    {
      id: 'family-celebration',
      number: '02',
      title: 'FAMILY & CELEBRATION EVENTS',
      description: 'Photography & Videography for Birthday Parties, Weddings, Reunions, Surprise Parties, Barasala Ceremonies, and Baby Showers.',
      image: '/service_family.jpg',
      features: [
        'Birthday Parties',
        'Weddings & Pre-Weddings',
        'Family Get-Togethers',
        'Surprise Parties',
        'Baby Showers & Barasala'
      ]
    },
    {
      id: 'traditional-cultural',
      number: '03',
      title: 'TRADITIONAL & CULTURAL EVENTS',
      description: 'Capturing Half Saree & Dhoti Ceremonies, Gruhapravesham, Satyanarayana Pooja, Temple Functions, and Ustavams.',
      image: '/pooja_ceremony.jpg',
      features: [
        'Half Saree Ceremonies',
        'Dhoti Ceremonies',
        'Gruhapravesham (Housewarming)',
        'Satyanarayana Pooja',
        'Temple Functions & Ustavams'
      ]
    },
    {
      id: 'corporate-professional',
      number: '04',
      title: 'CORPORATE & PROFESSIONAL EVENTS',
      description: 'Professional coverage for Store Openings, Ribbon Cutting Ceremonies, Business Launches, and Brand Promotional Events.',
      image: '/gym_store.jpg',
      features: [
        'Store Openings',
        'Ribbon Cutting Ceremonies',
        'Business Launch Events',
        'Brand Promotional Events',
        'Conferences & Seminars'
      ]
    },
    {
      id: 'media-content',
      number: '05',
      title: 'MEDIA & CONTENT PRODUCTION',
      description: 'High-quality Podcast Shoots, Talk Show Productions, Interview Sessions, and engaging Social Media Content & REEL shoots.',
      image: '/service_reel.jpg',
      features: [
        'Podcast Shoots',
        'Talk Show Productions',
        'Interview Sessions',
        'Social Media Content Creation',
        'Music Videos & Promos'
      ]
    },
    {
      id: 'promotional-shoots',
      number: '06',
      title: 'PROMOTIONAL SHOOTS',
      description: 'High-impact promotional videos, commercial shoots, and branding content tailored to elevate your business.',
      image: '/gym_store.jpg',
      features: [
        'Commercial Shoots',
        'Product Promos',
        'Brand Identity Campaigns',
        'Real Estate Walkthroughs',
        'Advertising Content'
      ]
    },
  ],
  portfolio: [
    {
      id: 3,
      title: 'CULT STORE 01',
      category: 'PROMOTIONAL',
      year: '2026',
      description: 'Premium store walkthrough and brand promotion.',
      image: 'https://img.youtube.com/vi/9-nnvOdWM2A/maxresdefault.jpg',
      video: 'https://www.youtube.com/embed/9-nnvOdWM2A?autoplay=1&mute=1&loop=1&playlist=9-nnvOdWM2A',
      featured: true,
    },
    {
      id: 2,
      title: 'CRICKET TOURNAMENT',
      category: 'EVENT',
      year: '2026',
      description: 'High energy sports coverage and cinematic highlights.',
      image: 'https://img.youtube.com/vi/PbmhdAOPRuk/maxresdefault.jpg',
      video: 'https://www.youtube.com/embed/PbmhdAOPRuk?autoplay=1&mute=1&loop=1&playlist=PbmhdAOPRuk',
      featured: true,
    },
    {
      id: 1,
      title: 'BIKE DELIVERY',
      category: 'CINEMATIC',
      year: '2026',
      description: 'Cinematic coverage of a brand new bike delivery experience.',
      image: 'https://img.youtube.com/vi/c4Bmc3-N67g/maxresdefault.jpg',
      video: 'https://www.youtube.com/embed/c4Bmc3-N67g?autoplay=1&mute=1&loop=1&playlist=c4Bmc3-N67g',
      featured: true,
    },
    {
      id: 4,
      title: 'CULT STORE 02',
      category: 'PROMOTIONAL',
      year: '2026',
      description: 'Dynamic fitness apparel and store cinematic.',
      image: 'https://img.youtube.com/vi/Ty2ElzVos3w/maxresdefault.jpg',
      video: 'https://www.youtube.com/embed/Ty2ElzVos3w?autoplay=1&mute=1&loop=1&playlist=Ty2ElzVos3w',
      featured: false,
    },
    {
      id: 5,
      title: 'FATHER\'S DAY',
      category: 'EVENT',
      year: '2026',
      description: 'Emotional and beautiful moments captured for Father\'s Day.',
      image: '/fathers_day.jpg',
      video: '/videos/fathers_day.mov',
      featured: false,
    },
    {
      id: 6,
      title: 'POOJA',
      category: 'EVENT',
      year: '2026',
      description: 'Traditional moments captured during a sacred Pooja ceremony.',
      image: '/pooja_ceremony.jpg',
      video: '/videos/pooja.mov',
      featured: false,
    },
    {
      id: 8,
      title: 'SCHOOL FUNCTION',
      category: 'EVENT',
      year: '2026',
      description: 'Vidhyardhi School annual day function and celebrations.',
      image: '/school_function.jpg',
      video: '/videos/school_function.mov',
      featured: false,
    },
    {
      id: 9,
      title: 'YOGA DAY KIDS',
      category: 'EVENT',
      year: '2026',
      description: 'Peaceful and cinematic coverage of kids on Yoga Day.',
      image: '/yoga_kids.jpg',
      video: '/videos/yoga_day_kids.mov',
      featured: false,
    },
  ],
  clientFilms: [
    {
      id: 1,
      title: 'INTO THE WILD',
      client: 'CLIENT NAME',
      category: 'CINEMATIC',
      year: '2026',
      thumbnail: '/drone_cinematic.jpg',
      video: '/videos/bike_delivery.mp4',
      description: 'A powerful cinematic piece crafted for an adventurous brand identity campaign.',
    },
    {
      id: 2,
      title: 'PULSE OF THE CITY',
      client: 'CLIENT NAME',
      category: 'PROMOTIONAL',
      year: '2026',
      thumbnail: '/event_cinematic.jpg',
      video: '/videos/cricket_tournament.mov',
      description: 'High-energy urban promotional video blending motion and music.',
    },
    {
      id: 3,
      title: 'FRAMES OF LIGHT',
      client: 'CLIENT NAME',
      category: 'FILMMAKING',
      year: '2026',
      thumbnail: '/story_section.jpg',
      video: '/videos/cult_store_01.mov',
      description: 'Short film commissioned for a cultural arts organisation.',
    },
    {
      id: 4,
      title: 'ABOVE & BEYOND',
      client: 'CLIENT NAME',
      category: 'DRONE',
      year: '2026',
      thumbnail: '/hero_cinematic.jpg',
      video: '/videos/fathers_day.mov',
      description: 'Aerial production for a luxury real estate project.',
    },
  ],
  clients: [
    'ACME PRODUCTIONS', 'NOVA EVENTS', 'APEX STUDIOS',
    'LUMINARY FILMS', 'STELLAR MEDIA', 'HORIZON BRANDS',
    'ZENITH CREATIVE', 'PRISM STUDIOS', 'ANCHOR MEDIA',
    'ECLIPSE FILMS', 'VORTEX EVENTS', 'CROWN VISUALS',
  ],
};
